{{- if .Values.postgresql.enabled }}
{{- $pg := .Values.postgresql.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgresql-url" (include "cnpj-data-publisher.fullname" .) }}
  labels:
    {{- include "cnpj-data-publisher.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ printf "postgresql+psycopg://%s:%s@%s-postgresql:5432/%s" $pg.username $pg.password .Release.Name $pg.database | quote }}
{{- end }}
